import createFetchClient, { type Client, type ClientOptions } from "openapi-fetch";
import createQueryBindings, { type OpenapiQueryClient } from "openapi-react-query";
import { isApiError } from "./api-error.js";
import {
  DEFAULT_LOGIN_PATH,
  defaultBaseUrl,
  newRequestId,
  redirectToLogin,
  throwIfNotOk,
  withDefaults,
  type RedirectFn,
} from "./request.js";

export interface CreateApiOptions {
  /** Default: the page origin. */
  baseUrl?: string;
  /** Extra headers sent with every request. */
  headers?: Record<string, string>;
  /** Injectable fetch (tests). Resolved per request, so msw and other patches of globalThis.fetch work. */
  fetch?: typeof globalThis.fetch;
  /** Called with the login URL on a 401. Default: `window.location.assign`. Injectable for tests. */
  redirect?: RedirectFn;
  /** Default "/auth/login". */
  loginPath?: string;
  /** Set false to disable the 401 redirect (the ApiError is still thrown). Default true. */
  redirectOn401?: boolean;
  /** Request id generator. Default: crypto.randomUUID. */
  requestId?: () => string;
}

/** The typed client plus the TanStack Query bindings. */
export type Api<Paths extends {}> = OpenapiQueryClient<Paths> & {
  /** Raw typed openapi-fetch client. Throws `ApiError` on any non-2xx response, so `error` is never populated. */
  client: Client<Paths>;
};

/**
 * Builds the playground API client from the `paths` type generated by openapi-typescript.
 *
 * Behavior added on top of openapi-fetch:
 * - `credentials: "include"` and a fresh `X-Request-Id` (UUID) per request;
 * - any non-2xx response throws `ApiError` (RFC 9457 problem+json from Huma), for the raw client and for the Query hooks;
 * - a 401 first redirects to `/auth/login?next=<current path+search>`, then throws.
 */
export function createApi<Paths extends {}>(opts: CreateApiOptions = {}): Api<Paths> {
  const requestId = opts.requestId ?? newRequestId;
  const redirectOn401 = opts.redirectOn401 ?? true;
  const loginPath = opts.loginPath ?? DEFAULT_LOGIN_PATH;

  const playgroundFetch = async (input: Request): Promise<Response> => {
    const doFetch = opts.fetch ?? globalThis.fetch;
    const res = await doFetch(withDefaults(input, requestId));
    if (res.status === 401 && redirectOn401) {
      const redirectOpts: Parameters<typeof redirectToLogin>[0] = { loginPath };
      if (opts.redirect) redirectOpts.redirect = opts.redirect;
      redirectToLogin(redirectOpts);
    }
    return throwIfNotOk(res);
  };

  const clientOptions: ClientOptions = {
    baseUrl: opts.baseUrl ?? defaultBaseUrl(),
    credentials: "include",
    fetch: playgroundFetch,
  };
  if (opts.headers) clientOptions.headers = opts.headers;

  const client = createFetchClient<Paths>(clientOptions);
  return { ...createQueryBindings(client), client };
}

/** Retry policy for QueryClient: never retry 4xx `ApiError`s, retry everything else up to 2 times. */
export function shouldRetry(failureCount: number, error: unknown): boolean {
  if (isApiError(error) && error.status >= 400 && error.status < 500) return false;
  return failureCount < 2;
}
